// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNx_F_1LTOqBJTSAznjrHTLE3TZKxLKw',
    appId: '1:960014127826:web:46f38a51d5cfea3483530b',
    messagingSenderId: '960014127826',
    projectId: 'crce-connex',
    authDomain: 'crce-connex.firebaseapp.com',
    databaseURL:
        'https://crce-connex-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crce-connex.appspot.com',
    measurementId: 'G-JSKV1RF0YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YoA-2Lg1uNLdVaoqqnuRfqHI4qUg490',
    appId: '1:960014127826:android:58d302ed9da749cf83530b',
    messagingSenderId: '960014127826',
    projectId: 'crce-connex',
    databaseURL:
        'https://crce-connex-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crce-connex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnq3GgxcNQDLZnbvKLEee_R5_0rV6OuY',
    appId: '1:960014127826:ios:6c22cc174af3436783530b',
    messagingSenderId: '960014127826',
    projectId: 'crce-connex',
    databaseURL:
        'https://crce-connex-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crce-connex.appspot.com',
    iosBundleId: 'com.example.flutterApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZnq3GgxcNQDLZnbvKLEee_R5_0rV6OuY',
    appId: '1:960014127826:ios:63709929073fdebc83530b',
    messagingSenderId: '960014127826',
    projectId: 'crce-connex',
    databaseURL:
        'https://crce-connex-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crce-connex.appspot.com',
    iosBundleId: 'com.example.flutterApps.RunnerTests',
  );
}
